apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-dino
  namespace: default           
  labels:
    app: demo-dino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-dino
  template:
    metadata:
      labels:
        app: demo-dino
    spec:
      containers:
        - name: demo-dino
          image: images-private.darkhive.ai/demo-dino:1.0.1
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: demo-dino
  namespace: default           
spec:
  type: NodePort
  selector:
    app: demo-dino
  ports:
    - name: http
      port: 80         
      targetPort: 80   
      nodePort: 30000
